/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-29 06:44:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Pivot &mdash; Website Template by Colorlib</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=K2D:400,700|Niramit:300,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme Style -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("    <header role=\"banner\">\r\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a class=\"navbar-brand position-absolute\" href=\"index.html\">Pivot</a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExample05\" aria-controls=\"navbarsExample05\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapse navbar-collapse position-relative\" id=\"navbarsExample05\">\r\n");
      out.write("            <ul class=\"navbar-nav mx-auto pl-lg-5 pl-0 d-flex align-items-center\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active\" href=\"index.html\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"services.html\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Services</a>\r\n");
      out.write("                <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Pre-Construction</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">General Construction</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">House Renovation</a>\r\n");
      out.write("                  <a class=\"dropdown-item\" href=\"services.html\">Plumbing</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"works.html\">Projects</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"news.html\">News</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"about.html\">About</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"contact.html\">Contact</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item cta-btn2\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"get-quote.html\">\r\n");
      out.write("                  <span class=\"d-inline-block px-4 py-2 border\">Quotation</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- END header -->\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"home-slider owl-carousel\">\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('img/slider-2.jpg');\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row slider-text align-items-center justify-content-center text-center\">\r\n");
      out.write("            <div class=\"col-md-7 col-sm-12 element-animate\">\r\n");
      out.write("              <h1 class=\"mb-4\"> Fastest-Growing Construction Company</h1>\r\n");
      out.write("              <p class=\"mb-0\"><a href=\"#\" target=\"_blank\" class=\"btn btn-primary\">Get Started</a></p>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"slider-item\" style=\"background-image: url('img/slider-1.jpg');\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row slider-text align-items-center justify-content-center text-center\">\r\n");
      out.write("            <div class=\"col-md-8 col-sm-12 element-animate\">\r\n");
      out.write("              <h1 class=\"mb-4\">We Are Leading The Way Construction Works</h1>\r\n");
      out.write("              <p class=\"mb-0\"><a href=\"#\" target=\"_blank\" class=\"btn btn-primary\">Get Started</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END slider -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-md-6 pr-lg-5 mb-5 mb-md-0  element-animate\">\r\n");
      out.write("            <div class=\"pr-lg-5\">\r\n");
      out.write("              <h2 class=\"text-uppercase heading border-bottom mb-4 text-left\">We Are Expert in <br>Construction Field</h2>\r\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam similique repellat dignissimos, omnis at ducimus pariatur odio praesentium eveniet porro sit quod, sequi unde atque magnam voluptate quae voluptatum. Delectus.</p>\r\n");
      out.write("              <p>At sed impedit, ab a officia blanditiis, fuga commodi delectus veniam architecto in nihil numquam eum maiores. Amet nihil, dolorum sit vitae fugit maxime earum optio culpa eum. Voluptates, labore.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6  element-animate\">\r\n");
      out.write("            <img src=\"img/work_thumb_1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"section border-t\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 element-animate\">\r\n");
      out.write("          <div class=\"col-md-8 text-center\">\r\n");
      out.write("            <h2 class=\"text-uppercase heading border-bottom mb-4\">Recent Projects</h2>\r\n");
      out.write("            <p class=\"mb-3 lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.</p>\r\n");
      out.write("            <p><a href=\"works.html\" class=\"btn btn-primary\">See All Projects</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("          <div class=\"col-md-4 element-animate\">\r\n");
      out.write("            <a href=\"works-single.html\" class=\"link-thumbnail\">\r\n");
      out.write("              <h3>House Renovation</h3>\r\n");
      out.write("              <span class=\"ion-plus icon\"></span>\r\n");
      out.write("              <img src=\"img/work_thumb_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 element-animate\">\r\n");
      out.write("            <a href=\"works-single.html\" class=\"link-thumbnail\">\r\n");
      out.write("              <h3>General Construction Building</h3>\r\n");
      out.write("              <span class=\"ion-plus icon\"></span>\r\n");
      out.write("              <img src=\"img/work_thumb_2.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 element-animate\">\r\n");
      out.write("            <a href=\"works-single.html\" class=\"link-thumbnail\">\r\n");
      out.write("              <h3>Pre-Construction</h3>\r\n");
      out.write("              <span class=\"ion-plus icon\"></span>\r\n");
      out.write("              <img src=\"img/work_thumb_3.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 element-animate\">\r\n");
      out.write("            <a href=\"works-single.html\" class=\"link-thumbnail\">\r\n");
      out.write("              <h3>House Renovation</h3>\r\n");
      out.write("              <span class=\"ion-plus icon\"></span>\r\n");
      out.write("              <img src=\"img/work_thumb_3.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 element-animate\">\r\n");
      out.write("            <a href=\"works-single.html\" class=\"link-thumbnail\">\r\n");
      out.write("              <h3>General Construction Building</h3>\r\n");
      out.write("              <span class=\"ion-plus icon\"></span>\r\n");
      out.write("              <img src=\"img/work_thumb_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 element-animate\">\r\n");
      out.write("            <a href=\"works-single.html\" class=\"link-thumbnail\">\r\n");
      out.write("              <h3>Pre-Construction</h3>\r\n");
      out.write("              <span class=\"ion-plus icon\"></span>\r\n");
      out.write("              <img src=\"img/work_thumb_2.jpg\" alt=\"Image placeholder\" class=\"img-fluid\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END section -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 element-animate\">\r\n");
      out.write("          <div class=\"col-md-8 text-center\">\r\n");
      out.write("            <h2 class=\"text-uppercase heading border-bottom mb-4\">Services</h2>\r\n");
      out.write("            <p class=\"mb-3 lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 col-12 mb-3 element-animate\">\r\n");
      out.write("            <div class=\"media d-block media-feature text-center\">\r\n");
      out.write("              <span class=\"flaticon-blueprint icon\"></span>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"mt-0 text-black\">Pre-Construction</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-outline-primary btn-sm\">Learn More</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 col-12 mb-3 element-animate\">\r\n");
      out.write("            <div class=\"media d-block media-feature text-center\">\r\n");
      out.write("              <span class=\"flaticon-building-1 icon\"></span>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"mt-0 text-black\">House Renovation</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-outline-primary btn-sm\">Learn More</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 col-12 mb-3 element-animate\">\r\n");
      out.write("            <div class=\"media d-block media-feature text-center\">\r\n");
      out.write("              <span class=\"flaticon-crane icon\"></span>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"mt-0 text-black\">General Contracting</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                <p><a href=\"#\" class=\"btn btn-outline-primary btn-sm\">Learn More</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- END row -->\r\n");
      out.write("        <div class=\"row justify-content-center element-animate\"> \r\n");
      out.write("          <div class=\"col-md-4\"><p><a href=\"services.html\" class=\"btn btn-primary btn-block\">View All Services</a></p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END section -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <section class=\"section bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 element-animate\">\r\n");
      out.write("          <div class=\"col-md-8 text-center mb-5\">\r\n");
      out.write("            <h2 class=\"text-uppercase heading border-bottom mb-4\">Our News</h2>\r\n");
      out.write("            <p class=\"mb-0 lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row element-animate\">\r\n");
      out.write("          <div class=\"major-caousel js-carousel-1 owl-carousel\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_1.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 8</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_2.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 2</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_3.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 5</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_1.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 7</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_2.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 1</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_3.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 4</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_1.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 12</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"media d-block media-custom text-left\">\r\n");
      out.write("                <img src=\"img/work_thumb_2.jpg\" alt=\"Image Placeholder\" class=\"img-fluid\">\r\n");
      out.write("                <div class=\"media-body\">\r\n");
      out.write("                  <span class=\"meta-post\">December 2, 2017</span>\r\n");
      out.write("                  <h3 class=\"mt-0 text-black\"><a href=\"#\" class=\"text-black\">Lorem ipsum dolor sit amet elit</a></h3>\r\n");
      out.write("                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\r\n");
      out.write("                  <p class=\"clearfix\">\r\n");
      out.write("                    <a href=\"#\" class=\"float-left\">Read more</a>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right meta-chat\"><span class=\"ion-chatbubble\"></span> 14</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- END slider -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END section -->\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 element-animate\">\r\n");
      out.write("          <div class=\"col-md-8 text-center mb-5\">\r\n");
      out.write("            <h2 class=\"text-uppercase heading border-bottom mb-4\">Happy Customer Says</h2>\r\n");
      out.write("            <p class=\"mb-0 lead\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 element-animate\">\r\n");
      out.write("            <div class=\"media d-block media-testimonial text-center\">\r\n");
      out.write("              <img src=\"img/person_1.jpg\" alt=\"Image placeholder\" class=\"img-fluid mb-3\">\r\n");
      out.write("              <p>Jane Doe, <a href=\"#\">XYZ Inc.</a></p>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <blockquote>\r\n");
      out.write("                  <p>&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.&rdquo;</p>  \r\n");
      out.write("                </blockquote>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-6 element-animate\">\r\n");
      out.write("            <div class=\"media d-block media-testimonial text-center\">\r\n");
      out.write("              <img src=\"img/person_3.jpg\" alt=\"Image placeholder\" class=\"img-fluid mb-3\">\r\n");
      out.write("              <p>John Doe, <a href=\"#\">XYZ Inc.</a></p>\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <blockquote>\r\n");
      out.write("                  <p>&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi unde impedit, necessitatibus, soluta sit quam minima expedita atque corrupti reiciendis.&rdquo;</p>  \r\n");
      out.write("                </blockquote>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"container cta-overlap\">\r\n");
      out.write("      <div class=\"text d-flex\">\r\n");
      out.write("        <h2 class=\"h3\">Contact Us For Projects or Need a Quotations</h2>\r\n");
      out.write("        <div class=\"ml-auto btn-wrap\">\r\n");
      out.write("          <a href=\"get-quote.html\" class=\"btn-cta btn btn-outline-white\">Get A Quote</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- END section -->\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"site-footer bg-dark\" role=\"contentinfo\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart text-danger\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\" >Colorlib</a>\r\n");
      out.write("            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <ul class=\"list-unstyled footer-link\">\r\n");
      out.write("              <li><span class=\"mr-3 d-block\">Address:</span><span class=\"text-white\">34 Street Name, City Name Here, United States</span></li>\r\n");
      out.write("              <li><span class=\"mr-3 d-block\">Phone:</span><span class=\"text-white\">+1 242 4942 290</span></li>\r\n");
      out.write("              <li><span class=\"mr-3 d-block\">Fax:</span><span class=\"text-white\">+1 242 4942 290</span></li>\r\n");
      out.write("              <li><span class=\"mr-3 d-block\">E-mail:</span><span class=\"text-white\">info@yourdomain.com</span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <h3 class=\"text-white\">Quick Links</h3>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link\">\r\n");
      out.write("              <li><a href=\"#\">About</a></li>\r\n");
      out.write("              <li><a href=\"#\">Services</a></li>\r\n");
      out.write("              <li><a href=\"#\">Works</a></li>\r\n");
      out.write("              <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3\">\r\n");
      out.write("            <h3 class=\"text-white\">Social</h3>\r\n");
      out.write("            <ul class=\"list-unstyled footer-link d-flex footer-social\">\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-twitter\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-facebook\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-linkedin\"></span></a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"p-2\"><span class=\"fa fa-instagram\"></span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- END footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- loader -->\r\n");
      out.write("    <div id=\"loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#f4b214\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
